### ISSUE TITLE
Wkhtmltopdf.NetCore.dll: 'Permission denied'

### ISSUE THREAD

**Issue by vinitecnico** [carloscds/HtmlToPDFCore#1]
How to resolve this error ?

Exception has occurred: CLR/System.ComponentModel.Win32Exception
An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in Wkhtmltopdf.NetCore.dll: 'Permission denied'
   at Wkhtmltopdf.NetCore.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html)
   at Wkhtmltopdf.NetCore.HtmlAsPdf.GetPDF(String html)
   at HtmlToPDFCore.HtmlToPDF.ReturnPDF(String html)
   at create_file_pdf.Program.GeneratePdfReport(IEnumerable`1 eventList) in /Users/niciuse/Desktop/work/create-file-pdf/Program.cs:line 27
   at create_file_pdf.Program.Main(String[] args) in /Users/niciuse/Desktop/work/create-file-pdf/Program.cs:line 17

**Comment by carloscds** [comment]
@vinitecnico Você tem permissao para gravar na pasta ? Se possível pasta aqui o codigo

**Comment by vinitecnico** [comment]
tenho sim, estou levando esse erro rodando no macOs, ou a dll não é compativel?

**Comment by vinitecnico** [comment]
estava vendo aqui ele no macOs ele roda isso não é do 'System.ComponentModel.Win32Exception' windows ou nada a ver ?

outra duvida é sobre as pastas de rotations, chegou a rodar em macOs e Linux ?

**Comment by carloscds** [comment]
@vinitecnico No MAC nao rodei, somente no Windows e Linux, você viu se as pastas estão la no diretório Rotativa ?
