### ISSUE TITLE
Issue Testing Nuget

### ISSUE THREAD

**Issue by jmarti326** [carloscds/HtmlToPDFCore#2]
Hi, Thank you for working on a tool like this.  I am writing to see if you could help me out solve this problem.

I am running the solution as shown in the example in a .NET Core 2.2 in Mac OS.
I am getting this Broken Pipe Error.

Is there something special that I should do?

{System.IO.IOException: Broken pipe
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Wkhtmltopdf.NetCore.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html)
   at HTML2PDF.Program.Main(String[] args) in /Users/jmarti/projects/HTML2PDF/HTML2PDF/Program.cs:line 17}
	Data: {System.Collections.ListDictionaryInternal}
	HResult: 32
	HelpLink: (null)
	InnerException: (null)
	Message: "Broken pipe"
	Source: "System.Private.CoreLib"
	StackTrace: "   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)\n   at System.IO.FileStream.FlushWriteBuffer()\n   at System.IO.FileStream.Dispose(Boolean disposing)\n   at System.IO.Stream.Close()\n   at System.IO.StreamWriter.Dispose(Boolean disposing)\n   at System.IO.TextWriter.Dispose()\n   at Wkhtmltopdf.NetCore.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html)\n   at HTML2PDF.Program.Main(String[] args) in /Users/jmarti/projects/HTML2PDF/HTML2PDF/Program.cs:line 17"
	TargetSite: {Void WriteNative(System.ReadOnlySpan`1[System.Byte])}
	Static members: 
	Non-Public members:

**Comment by carloscds** [comment]
@jmarti326 Your app has permission to write file ?
